### PR TITLE
Feature/continuous analysis

### PR DESCRIPTION
**Pull request by dlepaux**

### CODE REVIEW

**Comment by Bulinlinbu** [comment]
Hi David,
The server.js does nothing...

"Cannot GET /"

**Comment by dlepaux** [comment]
@Bulinlinbu please start the server from the realtime-bpm-analyzer-exemple folder (with the realtime-bpm-analyzer into app/components/...

**Comment by dlepaux** [comment]
@Bulinlinbu do you need some help ?

**Comment by Bulinlinbu** [comment]
Not help, just time...

I'll try soon !

**Comment by dlepaux** [comment]
@Bulinlinbu UP

**Comment by dlepaux** [comment]
@Bulinlinbu I close this PR but if you find some time you can always give me some returns about the project.

**Pull request merged**
